In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [3]:
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [4]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [5]:
df.shape

(5050, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [7]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

### EDA

In [8]:
df['Gender'].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [9]:
df['Item Purchased'].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [10]:
df['Category'].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [11]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [12]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [13]:
product_category = {
    # Clothing
    "T-shirt": "Clothing",
    "Shirt": "Clothing",
    "Shorts": "Clothing",
    "Hoodie": "Clothing",
    "Pants": "Clothing",
    "Socks": "Clothing",
    "Jeans": "Clothing",
    "Blouse": "Clothing",
    "Skirt": "Clothing",
    "Sweater": "Clothing",
    "Dress": "Clothing",

    # Footwear
    "Shoes": "Footwear",
    "Sandals": "Footwear",
    "Sneakers": "Footwear",
    "Boots": "Footwear",

    # Electronics
    "Laptop": "Electronics",
    "Phone": "Electronics",
    "Headphones": "Electronics",
    "Watch": "Electronics",

    # Accessories
    "Sunglasses": "Accessories",
    "Gloves": "Accessories",
    "Jewelry": "Accessories",
    "Hat": "Accessories",
    "Handbag": "Accessories",
    "Backpack": "Accessories",
    "Belt": "Accessories",
    "Scarf": "Accessories",
    "Bag": "Accessories",

    # Outerwear
    "Coat": "Outerwear",
    "Jacket": "Outerwear"
}

In [14]:
# correcting products in category
df["Category"] = df["Item Purchased"].map(product_category)

In [15]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [16]:
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [17]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [18]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [19]:
# filing size values in there category 
invalid_size_categories = ['Accessories', 'Electronics','Footwear']

df.loc[df['Category'].isin(invalid_size_categories), 'Size'] = 'Not_Applicable'

In [20]:
df.groupby('Category')['Size'].unique()

Category
Accessories      [Not_Applicable]
Clothing       [XL, M, S, L, nan]
Electronics      [Not_Applicable]
Footwear         [Not_Applicable]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [21]:
# Get mode for Clothing category
clothing_mode = df[df['Category'] == 'Clothing']['Size'].mode()[0]

# Fill null values in Clothing category
df.loc[
    (df['Category'] == 'Clothing') & (df['Size'].isna()),
    'Size'
] = clothing_mode

In [22]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [Not_Applicable]
Clothing          [XL, M, S, L]
Electronics    [Not_Applicable]
Footwear       [Not_Applicable]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [23]:
df.loc[df['Category'] == 'Footwear', 'Size'] = 'Not_Available'

In [24]:
df.groupby('Category')['Size'].unique()

Category
Accessories    [Not_Applicable]
Clothing          [XL, M, S, L]
Electronics    [Not_Applicable]
Footwear        [Not_Available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [25]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [26]:
df.groupby('Category')['Review Rating'].unique()

Category
Accessories    [3.9, 4.2, 3.6, 4.0, 4.3, 2.8, 3.2, 3.1, 3.8, 2.6, 4.6, 4.5, 4.7, nan, 3.4, 2.9, 3.0, 4.1, 2.5, 3.5, 4.4, 3.3, 3.7, 2.7, 4.8, 1.0, 4.9, 5.0, 2.0]
Clothing       [3.2, 3.1, 3.4, nan, 4.2, 4.8, 3.8, 3.3, 3.0, 4.5, 2.9, 4.1, 4.7, 4.6, 4.9, 2.8, 3.9, 3.6, 4.4, 5.0, 2.7, 2.6, 2.0, 3.5, 4.0, 4.3, 3.7, 2.5, 1.0]
Electronics                                                                                                                       [nan, 5.0, 1.0, 3.0, 2.0, 4.0]
Footwear       [nan, 3.2, 3.5, 4.0, 3.6, 3.9, 4.9, 3.4, 3.8, 3.0, 1.0, 4.8, 4.2, 2.7, 2.5, 3.1, 3.7, 3.3, 2.6, 4.1, 4.4, 4.7, 2.0, 4.5, 4.3, 2.9, 5.0, 4.6, 2.8]
Outerwear                [2.8, 2.5, 3.8, 4.1, 4.0, 4.4, 2.9, 3.6, 3.7, 2.6, 3.9, 3.5, 3.1, 4.9, 4.5, 3.4, 4.7, 4.6, 2.7, 3.3, 4.3, 4.8, 4.2, 5.0, 3.0, 3.2, nan]
Name: Review Rating, dtype: object

In [27]:
# filing reivew with there category based mean 
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(
    lambda x: x.fillna(x.mean())
)

In [28]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [29]:
df.groupby('Category')['Review Rating'].unique()

Category
Accessories    [3.9, 4.2, 3.6, 4.0, 4.3, 2.8, 3.2, 3.1, 3.8, 2.6, 4.6, 4.5, 4.7, 3.7287106446776606, 3.4, 2.9, 3.0, 4.1, 2.5, 3.5, 4.4, 3.3, 3.7, 2.7, 4.8, 1.0, 4.9, 5.0, 2.0]
Clothing        [3.2, 3.1, 3.4, 3.693307522123894, 4.2, 4.8, 3.8, 3.3, 3.0, 4.5, 2.9, 4.1, 4.7, 4.6, 4.9, 2.8, 3.9, 3.6, 4.4, 5.0, 2.7, 2.6, 2.0, 3.5, 4.0, 4.3, 3.7, 2.5, 1.0]
Electronics                                                                                                                        [3.071197411003236, 5.0, 1.0, 3.0, 2.0, 4.0]
Footwear       [3.7191964285714283, 3.2, 3.5, 4.0, 3.6, 3.9, 4.9, 3.4, 3.8, 3.0, 1.0, 4.8, 4.2, 2.7, 2.5, 3.1, 3.7, 3.3, 2.6, 4.1, 4.4, 4.7, 2.0, 4.5, 4.3, 2.9, 5.0, 4.6, 2.8]
Outerwear                   [2.8, 2.5, 3.8, 4.1, 4.0, 4.4, 2.9, 3.6, 3.7, 2.6, 3.9, 3.5, 3.1, 4.9, 4.5, 3.4, 4.7, 4.6, 2.7, 3.3, 4.3, 4.8, 4.2, 5.0, 3.0, 3.2, 3.7420245398773]
Name: Review Rating, dtype: object

In [30]:
df['Review Rating'] = df['Review Rating'].round(2)

In [31]:
df.groupby('Category')['Review Rating'].unique()

Category
Accessories    [3.9, 4.2, 3.6, 4.0, 4.3, 2.8, 3.2, 3.1, 3.8, 2.6, 4.6, 4.5, 4.7, 3.73, 3.4, 2.9, 3.0, 4.1, 2.5, 3.5, 4.4, 3.3, 3.7, 2.7, 4.8, 1.0, 4.9, 5.0, 2.0]
Clothing       [3.2, 3.1, 3.4, 3.69, 4.2, 4.8, 3.8, 3.3, 3.0, 4.5, 2.9, 4.1, 4.7, 4.6, 4.9, 2.8, 3.9, 3.6, 4.4, 5.0, 2.7, 2.6, 2.0, 3.5, 4.0, 4.3, 3.7, 2.5, 1.0]
Electronics                                                                                                                       [3.07, 5.0, 1.0, 3.0, 2.0, 4.0]
Footwear       [3.72, 3.2, 3.5, 4.0, 3.6, 3.9, 4.9, 3.4, 3.8, 3.0, 1.0, 4.8, 4.2, 2.7, 2.5, 3.1, 3.7, 3.3, 2.6, 4.1, 4.4, 4.7, 2.0, 4.5, 4.3, 2.9, 5.0, 4.6, 2.8]
Outerwear                [2.8, 2.5, 3.8, 4.1, 4.0, 4.4, 2.9, 3.6, 3.7, 2.6, 3.9, 3.5, 3.1, 4.9, 4.5, 3.4, 4.7, 4.6, 2.7, 3.3, 4.3, 4.8, 4.2, 5.0, 3.0, 3.2, 3.74]
Name: Review Rating, dtype: object

In [32]:
df['Previous Purchases'] = df['Previous Purchases'].fillna(0)

In [33]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [34]:
df.groupby('Category')['Purchase Amount (USD)'].unique()

Category
Accessories                                                                                                                                                                                [84.0, 75.0, 80.0, 93.0, 65.0, 60.0, 47.0, 71.0, 34.0, 31.0, 30.0, 24.0, 56.0, nan, 46.0, 32.0, 52.0, 53.0, 44.0, 208.02, 64.0, 23.0, 50.0, 95.0, 69.0, 96.0, 94.0, 34.65, 33.0, 66.0, 57.0, 25.0, 70.0, 39.0, 58.0, 36.0, 99.0, 97.0, 78.0, 48.0, 22.0, 20.0, 68.0, 21.0, 76.0, 49.0, 90.0, 81.0, 35.0, 26.0, 74.0, 38.0, 92.0, 187.34, 40.0, 42.0, 82.06, 1002.35, 82.0, 62.0, 27.0, 77.0, 1246.93, 316.21, 29.0, 98.0, 41.0, 54.0, 63.0, 1170.25, 253.94, 468.46, 89.0, 55.0, 91.0, 51.0, 67.0, 61.0, 781.26, 1311.75, 87.0, 59.0, 72.0, 100.0, 83.0, 88.0, 28.0, 607.15, 611.08, 85.0, 896.53, 489.56, 843.8, 73.0, 236.32, 1270.13, 37.0, 86.0, 551.22, 873.21, ...]
Clothing                                                                                                                                                                                        [68.0, 50.0, 41.0, 81.0, 20.0, 88.0, 75.0, 23.0, 83.0, 26.0, 45.0, 70.0, 91.0, 55.0, 57.0, 95.0, 86.0, 53.0, 557.24, 692.11, 84.0, 1398.9, 52.0, 85.0, 33.0, 64.0, 73.0, 77.0, nan, 89.0, 76.0, 74.0, 67.0, 1342.62, 54.0, 78.0, 32.0, 48.0, 82.0, 93.0, 46.0, 56.0, 59.0, 97.0, 24.0, 44.0, 66.0, 80.0, 94.0, 450.41, 72.0, 96.0, 100.0, 36.0, 30.0, 40.0, 38.0, 60.0, 35.0, 29.0, 87.0, 25.0, 65.0, 28.0, 34.0, 51.0, 71.0, 62.0, 99.0, 31.0, 42.0, 1322.78, 238.88, 58.0, 49.0, 92.0, 43.0, 39.0, 21.0, 22.0, 63.0, 90.0, 1103.36, 560.62, 75.12, 98.0, 37.0, 47.0, 61.0, 175.4, 79.0, 780.59, 230.19, 379.18, 27.0, 336.09, 1352.6, 591.76, 949.74, 914.23, ...]
Electronics    [884.04, nan, 1032.09, 1282.44, 748.61, 500.3, 498.03, 1392.02, 532.49, 95.15, 105.21, 854.96, 585.1, 495.98, 1366.1, 772.94, 1430.07, 1186.98, 1223.83, 297.78, 1318.69, 719.91, 1067.74, 116.74, 685.22, 19.69, 742.32, 243.4, 571.08, 964.07, 1192.93, 943.94, 921.94, 390.76, 104.65, 478.29, 767.36, 640.27, 43.99, 690.65, 1388.53, 939.3, 889.78, 1207.32, 966.98, 310.29, 193.65, 119.25, 282.95, 860.91, 1186.38, 220.25, 69.72, 1033.69, 1069.81, 581.66, 1410.28, 543.93, 1294.07, 1459.71, 509.47, 372.79, 851.29, 464.46, 157.83, 1208.85, 1224.96, 988.27, 387.35, 1147.1, 335.78, 629.99, 356.1, 684.07, 722.83, 1311.16, 1493.56, 732.58, 183.76, 1459.59, 822.03, 992.57, 1006.01, 728.44, 1025.56, 1436.38, 187.51, 469.48, 1403.73, 736.01, 118.61, 789.72, 510.59, 627.73, 749.08, 1104.47, 784.97, 377.18, 639.97, 1495.94, ...]
Footwear                                                                                                                                                                    [nan, 49.0, 59.0, 68.0, 83.0, 66.0, 43.0, 99.0, 69.0, 390.25, 21.0, 22.0, 96.0, 1312.35, 87.0, 74.0, 60.0, 85.0, 71.0, 24.0, 39.0, 63.0, 50.0, 92.0, 55.0, 54.0, 758.1, 1438.53, 64.0, 585.85, 32.0, 98.0, 1277.16, 44.0, 67.0, 309.93, 45.0, 90.0, 91.0, 26.0, 40.0, 72.0, 20.0, 65.0, 638.81, 1426.64, 78.0, 97.0, 53.0, 36.0, 79.0, 890.97, 35.0, 88.0, 73.0, 51.0, 347.55, 370.41, 76.0, 56.0, 34.0, 23.0, 196.05, 81.0, 1090.49, 82.0, 859.84, 33.0, 48.0, 1357.03, 643.57, 86.0, 41.0, 38.0, 70.0, 28.0, 201.93, 62.0, 94.0, 75.0, 61.0, 37.0, 89.0, 1151.72, 47.0, 80.0, 1282.12, 93.0, 100.0, 991.93, 835.52, 598.48, 84.0, 412.8, 632.95, 478.64, 454.0, 58.0, 95.0, 31.0, ...]
Outerwear                                                                                                                                                                                                                                                                                                                                                    [24.0, 80.0, 33.0, 25.0, 31.0, 44.0, 28.0, 95.0, 97.0, 90.0, 32.0, 67.0, 77.0, 56.0, 84.0, 53.0, 93.0, 45.0, 35.0, 81.0, 75.0, 26.0, 100.0, 39.0, 36.0, 96.0, 86.0, 72.0, 85.0, 88.0, 30.0, 64.0, 58.0, 76.0, 37.0, 57.0, 34.0, 20.0, 99.0, 23.0, 43.0, 55.0, 82.0, 38.0, 92.0, 42.0, 68.0, 48.0, 22.0, 51.0, 61.0, 70.0, 59.0, 65.0, 71.0, 87.0, 66.0, 27.0, 91.0, 40.0, 94.0, 46.0, 89.0, 83.0, 21.0, 29.0, 63.0, 41.0, 54.0, 50.0, 98.0, 47.0, 60.0, 79.0, 78.0, 73.0, 62.0, 74.0, 52.0, 49.0, 69.0]
Name: Purchase Amount (USD), dtype: object

In [35]:
# filing values of purchase amount with there respective category with median

df['Purchase Amount (USD)'] = df.groupby('Category')['Purchase Amount (USD)'].transform(
    lambda x: x.fillna(x.median())
)

In [36]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [37]:
# corrcting columns names 
import re

df.columns = [
    re.sub(r'[^a-z0-9_]', '', col.lower().replace(' ', '_'))
    for col in df.columns
]

In [38]:
# renaming column 
df.rename(columns={"purchase_amount_usd ": "purchase_amount"}, inplace=True)

In [39]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_usd       0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

### Checking Duplicates

In [40]:
df[df.duplicated()]

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.30,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,Not_Applicable,Charcoal,Winter,3.10,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.50,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,Not_Available,Maroon,Winter,2.90,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,Not_Available,Orange,Winter,2.80,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,Not_Applicable,Olive,Spring,4.60,No,Express,No,50.0,PayPal,Bi-Weekly
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.70,No,Standard,No,13.0,Venmo,Annually
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,Not_Applicable,Blue,Summer,3.60,No,Standard,No,33.0,Bank Transfer,Annually
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.20,No,Next Day Air,No,31.0,PayPal,Bi-Weekly
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,Not_Applicable,Peach,Summer,3.73,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.80,No,Express,No,28.0,Cash,Fortnightly
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.80,No,Next Day Air,No,6.0,PayPal,Every 3 Months
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.70,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,Not_Applicable,Peach,Fall,4.20,No,Free Shipping,Yes,48.0,PayPal,Annually
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.80,No,Store Pickup,No,28.0,Cash,Annually
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.90,No,Standard,No,6.0,PayPal,Weekly
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,Not_Applicable,Black,Summer,3.90,No,Store Pickup,No,44.0,Venmo,Monthly
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,Not_Applicable,Turquoise,Winter,4.00,No,Next Day Air,No,41.0,Venmo,Fortnightly
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.20,No,Express,No,3.0,PayPal,Monthly
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,Not_Applicable,Red,Summer,4.50,Yes,Express,Yes,5.0,Credit Card,Quarterly
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,Not_Applicable,Brown,Summer,3.90,No,Express,No,40.0,Debit Card,Quarterly
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,Not_Available,Cyan,Fall,4.60,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.90,No,Store Pickup,No,15.0,Bank Transfer,Quarterly
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,Not_Available,Lavender,Summer,4.20,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.50,No,Next Day Air,No,48.0,Credit Card,Every 3 Months
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,Not_Available,Red,Winter,3.72,No,2-Day Shipping,Yes,8.0,Debit Card,Annually
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.60,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,Not_Applicable,Cyan,Winter,3.00,Yes,Standard,Yes,47.0,Credit Card,Monthly
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.40,No,Next Day Air,No,34.0,Debit Card,Annually
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,Not_Applicable,Lavender,Winter,4.00,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.90,No,Standard,No,17.0,PayPal,Fortnightly
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.70,No,2-Day Shipping,No,12.0,Cash,Fortnightly
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.00,No,Express,No,4.0,Venmo,Fortnightly
4059,227,29,Male,Shoes,Footwear,74.0,Texas,Not_Available,Violet,Spring,3.30,Yes,Free Shipping,Yes,5.0,PayPal,Monthly
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,Not_Applicable,Olive,Winter,2.70,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.80,No,Free Shipping,Yes,5.0,Debit Card,Monthly
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,Not_Applicable,Orange,Fall,3.40,No,Free Shipping,No,2.0,Bank Transfer,Monthly
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.90,No,Standard,No,46.0,Venmo,Annually
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,Not_Applicable,Magenta,Fall,3.20,No,Standard,No,47.0,Debit Card,Annually
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.90,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,Not_Applicable,Lavender,Spring,4.60,No,Standard,Yes,14.0,Debit Card,Bi-Weekly
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.90,No,2-Day Shipping,No,46.0,Credit Card,Monthly
4595,3577,29,Female,Boots,Footwear,24.0,Maine,Not_Available,Yellow,Spring,3.00,No,Express,No,12.0,Venmo,Bi-Weekly
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,Not_Applicable,Turquoise,Spring,2.90,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.90,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,Not_Applicable,Black,Fall,3.20,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,Not_Available,Beige,Winter,3.00,No,Express,No,21.0,Bank Transfer,Annually
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.90,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.50,No,Standard,Yes,25.0,Debit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.00,No,Store Pickup,No,33.0,Credit Card,Monthly

In [41]:
df[df['customer_id'] == 1060]

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
804,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.5,No,Standard,Yes,25.0,Debit Card,Monthly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.5,No,Standard,Yes,25.0,Debit Card,Monthly

In [42]:
# removing duplicates
df = df.drop_duplicates(subset = ['customer_id'], keep = 'first')

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df.count()

customer_id               5000
age                       5000
gender                    5000
item_purchased            5000
category                  5000
purchase_amount_usd       5000
location                  5000
size                      5000
color                     5000
season                    5000
review_rating             5000
subscription_status       5000
shipping_type             5000
discount_applied          5000
previous_purchases        5000
payment_method            5000
frequency_of_purchases    5000
dtype: int64

In [45]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Not_Applicable,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Not_Applicable,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Not_Applicable,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

##  now connect data to posgreSQL

In [50]:
!{sys.executable} -m pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 844.8 kB/s eta 0:00:03
   ------- -------------------------------- 0.5/2.7 MB 844.8 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.7 MB 795.6 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.7 MB 949.3 kB/s eta 0:00:02
   ----------------------- ---------------- 1.6/2.7 MB 1.2 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 1.5 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 1.3 MB/s  0:00:02
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [54]:
from sqlalchemy import create_engine

username = "postgres"
password = "778602"   # same as pgAdmin
host = "localhost"
port = "5432"
database = "customer_behaviour_analysis"        # the one you created

engine = create_engine(f'postgresql://{username}:{password}@{host}:{port}/{database}')

In [55]:
df.to_sql('customer_behaviour', engine, if_exists='replace', index=False)

1000

In [56]:
len(df)

5000